apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "sample-spring-boot-app-k8s"
spec:
  project: default
  source:
    path: manifests
    repoURL: 
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m